import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";
import { PILOT } from "./helpers";

/**
 * Past-papers PDF viewer E2E (operator audit s140) — this surface previously
 * had ZERO E2E coverage: the viewer is a client-side pdf.js canvas stack, so
 * nothing else in the suite would notice a regression in rendering, find,
 * page navigation, rotation, or the mock flow's links.
 *
 * Determinism: the corpus PDFs stream from raw.githubusercontent.com — every
 * test intercepts that host and serves tests/fixtures/pp-viewer.pdf (3 text
 * pages, generated by scripts/s140_fixture_pdf.py). No network, no flaky
 * archive, real pdf.js worker + rendering pipeline.
 *
 * The axe gate mirrors a11y.spec.ts: no CRITICAL/SERIOUS violations on the
 * loaded viewer (toolbar buttons, page inputs, the focusable pages region).
 */

const PAPER_URL = `/courses/${PILOT}/past-papers/view/2019-06/4CH1-1C`;
const FIXTURE = "tests/fixtures/pp-viewer.pdf";

test.beforeEach(async ({ page }) => {
  await page.route("**/raw.githubusercontent.com/**", (route) =>
    route.fulfill({ path: FIXTURE, contentType: "application/pdf" }),
  );
});

async function readyViewer(page: import("@playwright/test").Page) {
  await page.goto(`${PAPER_URL}?doc=qp`, { waitUntil: "load" });
  // the first canvas paints once the (tiny) fixture streams + renders
  await expect(
    page.locator(".pp-pane canvas").first(),
    "the question paper paints its pages",
  ).toBeVisible({ timeout: 20_000 });
}

test("viewer: pages render, indicator reads 1 / 3, unpainted holders show ghosts", async ({ page }) => {
  await readyViewer(page);
  await expect(page.getByRole("img", { name: "Page 1 of 3" })).toBeVisible();
  await expect(page.getByRole("img", { name: "Page 3 of 3" })).toBeVisible();
  const holders = page.locator(".pp-holder");
  await expect(holders).toHaveCount(3);
  // the page input reflects page 1
  await expect(page.getByLabel("Page number of 3")).toHaveValue("1");
  // ghost labels exist for any page outside the render window (all 3 are
  // within radius on the fixture, so assert the CSS contract instead)
  const ghostCss = await page.evaluate(() => {
    for (const sheet of document.styleSheets) {
      try {
        for (const rule of sheet.cssRules) {
          if (rule.cssText.includes(".pp-holder:empty::after")) return rule.cssText;
        }
      } catch {
        /* cross-origin sheet */
      }
    }
    return null;
  });
  expect(ghostCss, "the Page-N ghost rule is compiled").toContain("attr(data-page)");
});

test("viewer: typing a page number jumps (indicator follows)", async ({ page }) => {
  await readyViewer(page);
  const input = page.getByLabel("Page number of 3");
  await input.click();
  await input.fill("3");
  await input.press("Enter");
  await input.press("Tab"); // blur — the draft then follows the tracked page
  await expect
    .poll(async () => input.inputValue(), { timeout: 10_000 })
    .toBe("3");
  // an out-of-range draft clamps to the last page
  await input.click();
  await input.fill("99");
  await input.press("Enter");
  await expect(input).toHaveValue("3");
});

test("viewer: find bar searches, highlights, and steps through matches", async ({ page }) => {
  await readyViewer(page);
  await page.getByRole("button", { name: "Find in document" }).click();
  const findInput = page.getByPlaceholder("Find in document…");
  // the fixture has "magnesium chloride" on pages 1 and 2 (2 matches)
  await findInput.fill("magnesium chloride");
  await expect
    .poll(async () => page.locator(".pp-hl").count(), { timeout: 20_000 })
    .toBeGreaterThanOrEqual(2);
  await expect(findInput).toBeFocused();
  // Enter steps to the next match (the current highlight moves)
  await findInput.press("Enter");
  await expect(page.locator(".pp-hl.pp-hl-current").first()).toBeVisible();
  // Escape closes the bar and clears the highlights
  await findInput.press("Escape");
  await expect(page.locator(".pp-hl")).toHaveCount(0);
  // reopening re-shows the live results (s140 B2 regression pin)
  await page.getByRole("button", { name: "Find in document" }).click();
  await expect
    .poll(async () => page.locator(".pp-hl").count(), { timeout: 10_000 })
    .toBeGreaterThanOrEqual(2);
});

test("viewer: rotate 90° swaps the page aspect and keeps painting", async ({ page }) => {
  await readyViewer(page);
  const pane = page.locator(".pp-pane").first();
  await expect(pane).toHaveAttribute("data-rot", "0");
  const holder = page.getByRole("img", { name: "Page 1 of 3" });
  const before = (await holder.boundingBox())!;
  expect(before.height).toBeGreaterThan(before.width); // A4 portrait
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await expect(pane).toHaveAttribute("data-rot", "90");
  const after = (await holder.boundingBox())!;
  expect(after.width, "rotated holder is landscape").toBeGreaterThan(after.height);
  // the canvas survives the rotation re-render (double-buffered)
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await page.getByRole("button", { name: /Rotate 90 degrees/ }).click();
  await expect(pane).toHaveAttribute("data-rot", "0");
});

test("viewer: zoom ladder shows honest round steps and resets", async ({ page }) => {
  await readyViewer(page);
  const zoomIn = page.getByRole("button", { name: "Zoom in" });
  const zoomOut = page.getByRole("button", { name: "Zoom out" });
  const reset = page.getByRole("button", { name: "Reset to fit width" });
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  // s141: the ladder descends below fit-width — zoom-out is live at 100%
  await expect(zoomOut).toBeEnabled();
  await zoomIn.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 125% of fit width");
  await zoomIn.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 150% of fit width");
  await reset.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  // the below-fit overview steps (operator: "Ability to zoom out the pdf a
  // bit more" — 75%, then the 50% floor where the button disables)
  const holder = page.getByRole("img", { name: "Page 1 of 3" });
  const fitW = (await holder.boundingBox())!.width;
  await zoomOut.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 75% of fit width");
  await zoomOut.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 50% of fit width");
  await expect(zoomOut).toBeDisabled();
  // the page physically shrinks to ~half width (centered via mx-auto) and
  // the canvas survives the refit (double-buffered — never blanks)
  await expect
    .poll(async () => (await holder.boundingBox())?.width, { timeout: 5_000 })
    .toBeLessThan(fitW * 0.8);
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible();
  // reset is enabled while BELOW fit (the old <= floor kept it disabled)
  await expect(reset).toBeEnabled();
  await reset.click();
  await expect(zoomIn).toHaveAttribute("title", "Zoom: 100% of fit width");
  await expect(zoomOut).toBeEnabled();
});

test("viewer: split view shows QP and MS panes side by side", async ({ page }) => {
  await page.goto(`${PAPER_URL}?doc=split`, { waitUntil: "load" });
  const panes = page.locator(".pp-pane");
  await expect(panes).toHaveCount(2);
  for (const pane of await panes.all()) {
    await expect(pane.locator("canvas").first()).toBeVisible({ timeout: 20_000 });
  }
  // s140 audit regression pin: the split grid's implicit row used to grow to
  // the full document height — panes never bounded their scrollers, the
  // VISIBLE pages stayed blank and canvases rendered ~14 pages down.
  const state = await page.evaluate(() =>
    [...document.querySelectorAll(".pp-pane")].map((p) => {
      const scroller = p.querySelector("[role='region']");
      return {
        scrollerH: scroller ? Math.round(scroller.getBoundingClientRect().height) : 0,
        firstPagePainted: (p.querySelector(".pp-holder")?.childElementCount ?? 0) > 0,
      };
    }),
  );
  expect(state, "two panes inspected").toHaveLength(2);
  for (const s of state) {
    expect(s.scrollerH, "split scroller is viewport-bounded, not document-height").toBeLessThan(2000);
    expect(s.firstPagePainted, "the visible first page holds a canvas").toBe(true);
  }
});

test("mock: 'Just view the paper' lands on the viewer (s140 B1 404 pin)", async ({ page }) => {
  await page.goto(`${PAPER_URL}?mode=mock`, { waitUntil: "load" });
  await page.getByRole("link", { name: "Just view the paper" }).click();
  await expect(page).toHaveURL(new RegExp(`/past-papers/view/2019-06/4CH1-1C`));
  await expect(page.locator(".pp-pane canvas").first()).toBeVisible({ timeout: 20_000 });
});

test("viewer: the loaded page has no serious or critical axe violations", async ({ page }) => {
  await readyViewer(page);
  const results = await new AxeBuilder({ page }).analyze();
  const serious = results.violations.filter(
    (v) => v.impact === "critical" || v.impact === "serious",
  );
  for (const v of serious) {
    console.error(`[axe:pp-viewer] ${v.id} (${v.impact}) x${v.nodes.length}: ${v.help}`);
  }
  expect(serious, "pp-viewer: serious/critical a11y violations").toEqual([]);
});
